# Generated by Django 5.2.9 on 2025-12-21 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('location', models.CharField(blank=True, max_length=50)),
                ('tel', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
